### ISSUE TITLE
Change Windows drive

### ISSUE THREAD

**Issue by JoePue** [Tyriar/vscode-terminal-here#4]
If I have a file "E:\testdir\test.txt" and i want open a terminal on this drive in this folder, then your extension works not correctly, because your extension will not change the drive by enter "E:". Actually the executed command "cd E:\testdir" is not enough for windows.
Could you please extend your extension and support different windows drives. 
Best regards
Joe

**Comment by JoePue** [comment]
How can I help you? (I'am not really understood the 'help wanted' tag)

**Comment by Tyriar** [comment]
I'm open to accepting a PR, you would need to add some special logic for Windows in https://github.com/Tyriar/vscode-terminal-here/blob/master/src/extension.ts to check if there is a drive letter.

**Comment by noman9607** [comment]
Are you new? This is simple, just use the /d flag like this: "CD /D path-filename". We are talking dos 2 or 3, like the early eighties. Type cd /? in your console window and read all about it. There is no penalty for using the d flag when you do not need it. This is how I edit your command so that it will work.

**Comment by Tyriar** [comment]
@noman9607 feel free to make a PR to improve it, lose the attitude though.
